### ISSUE TITLE
Unable to transmitt frame with a dlc not equal to 8.

### ISSUE THREAD

**Issue by semicolonTransistor** [astuff/kvaser_interface#44]
I have been trying to send a can frame with dlc of 5 and kept getting error code -9(DLC_LENGTH_MISMATCH). Upon looking into the source code it seemed to have been produced by the following lines in KvaserCan::write (lines 246-247 in kvaser_interface.cpp)
```
if (payload_size != msg.data.size())
    return ReturnStatuses::DLC_PAYLOAD_MISMATCH;
```
  Since in Kinetic( I am not sure of other distros) the data field in can_msgs/Frame is defined as a fixed length boost array with length 8 there is no way to modify the size of this array prior to sending it to the kvaser_can_bridge.
```
   typedef boost::array<uint8_t, 8>  _data_type;
  _data_type data;
```
  Couple this with the fact that the dlc is check against this size exactly results any dlc not equal to 8 throwing the -9 error. While I see the reason in the size check to prevent out-of-bound accesses, I think this check is too strict. A check to make sure the dlc is not greater than the size of the data array would prevent the possibility of out-of-bound access while allowing messages with a shorter dlc to be sent. I have compiled and tested a version of the code with the aforementioned changes and it seemed to have fixed the original issue without any problems. 
```
  if (payload_size > msg.data.size())
    return ReturnStatuses::DLC_PAYLOAD_MISMATCH;
```

**Comment by JWhitleyAStuff** [comment]
@semicolonTransistor - Would you mind answering a few questions really quickly to help with the issue resolution process?

OS Name:
OS Version:
Built from Source or Installed with Apt:
Installed Version/Commit hash:

**Comment by semicolonTransistor** [comment]
Our system is running Ubuntu 16.04 LTS.
The ROS distro is Kinetic.
The linuxCAN library was installed with apt according to instruction provided in the readme.
The kvaser_interface installed was built from source using the latest release (4.0.3)
Hope this info helps.

**Comment by JWhitleyAStuff** [comment]
@semicolonTransistor Thanks for the data. Are you using the `linuxcan` library from this package directly or using the provided bridge node?

**Comment by semicolonTransistor** [comment]
We have been using the bridge node.

**Comment by JWhitleyAStuff** [comment]
@semicolonTransistor - Since 4.0.3, more changes have been introduced - specifically one fixing this problem. Check out lines [111](https://github.com/astuff/kvaser_interface/blob/26978ba96e14073558e36c9992047c5fc466ec9b/src/kvaser_can_bridge.cpp#L111) to [116](https://github.com/astuff/kvaser_interface/blob/26978ba96e14073558e36c9992047c5fc466ec9b/src/kvaser_can_bridge.cpp#L116) of the kvaser_can_bridge.cpp file. The code now looks up the appropriate number of bytes based on the DLC and only copies those bytes from the can_msgs/Frame into the `linuxcan` interface for transmission. Can you please test this version from source and see if it solves your problem?

**Comment by semicolonTransistor** [comment]
Sounds good, I'll test the latest version as soon as possible, probably tomorrow morning.

**Comment by semicolonTransistor** [comment]
Yep, I just tested it and it is working. I'll close this issue.
