### ISSUE TITLE
How to use this package in ROS2？

### ISSUE THREAD

**Issue by CrisFLZs** [astuff/kvaser_interface#91]
Sorry to bother you. I want to use the package in ROS2 building by ros-eloquent enviroment. But it seems hard to do that. Could you please give me some suggestions. Thanks a lot.

**Comment by icolwell-as** [comment]
Hi @CrisFLZs , this repo contains a `ros2_master` branch that might work for you. If it doesn't compile, it could be because of breaking API changes between the ROS2 versions (some node lifecycle stuff changed at some point which may break builds). 

That being said, the Eloquent release is now End-Of-Life, so I suggest moving to something like Humble, where this package is available via apt (see the README), since you may run into issues with other packages as well.
